version: 2
jobs:
  init:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Initial
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker: 
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

  publish:
    docker: 
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - run:
          name: Auth NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: npm publish

  release:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install PKG
          command: npm install --no-save pkg
      - run:
          name: Deploy
          command: yarn pkg bin/index.js
      - store_artifacts:
          path: ./index-linux
          destination: kommit-linux
      - store_artifacts:
          path: ./index-macos
          destination: kommit-macos
      - store_artifacts:
          path: ./index-win.exe
          destination: kommit-win.exe

workflows:
  version: 2
  test_and_publish:
    jobs:
      - init
      - test:
          requires:
            - init
      - release:
          requires:
            - test
          filters:
            branches:
              only: maste
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
